'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceGuia
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://service.sunat.gob.pe", ConfigurationName:="ServiceGuia.billService")>  _
    Public Interface billService
        
        'CODEGEN: El parámetro 'status' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:getStatus", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getStatus(ByVal request As ServiceGuia.getStatusRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="status")> ServiceGuia.getStatusResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:getStatus", ReplyAction:="*")>  _
        Function getStatusAsync(ByVal request As ServiceGuia.getStatusRequest) As System.Threading.Tasks.Task(Of ServiceGuia.getStatusResponse)
        
        'CODEGEN: El parámetro 'applicationResponse' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sendBill", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sendBill(ByVal request As ServiceGuia.sendBillRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="applicationResponse")> ServiceGuia.sendBillResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sendBill", ReplyAction:="*")>  _
        Function sendBillAsync(ByVal request As ServiceGuia.sendBillRequest) As System.Threading.Tasks.Task(Of ServiceGuia.sendBillResponse)
        
        'CODEGEN: El parámetro 'ticket' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sendPack", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sendPack(ByVal request As ServiceGuia.sendPackRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="ticket")> ServiceGuia.sendPackResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sendPack", ReplyAction:="*")>  _
        Function sendPackAsync(ByVal request As ServiceGuia.sendPackRequest) As System.Threading.Tasks.Task(Of ServiceGuia.sendPackResponse)
        
        'CODEGEN: El parámetro 'ticket' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sendSummary", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sendSummary(ByVal request As ServiceGuia.sendSummaryRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="ticket")> ServiceGuia.sendSummaryResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:sendSummary", ReplyAction:="*")>  _
        Function sendSummaryAsync(ByVal request As ServiceGuia.sendSummaryRequest) As System.Threading.Tasks.Task(Of ServiceGuia.sendSummaryResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.sunat.gob.pe")>  _
    Partial Public Class statusResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private contentField() As Byte
        
        Private statusCodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=0)>  _
        Public Property content() As Byte()
            Get
                Return Me.contentField
            End Get
            Set
                Me.contentField = value
                Me.RaisePropertyChanged("content")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property statusCode() As String
            Get
                Return Me.statusCodeField
            End Get
            Set
                Me.statusCodeField = value
                Me.RaisePropertyChanged("statusCode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatus", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class getStatusRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public ticket As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String)
            MyBase.New
            Me.ticket = ticket
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getStatusResponse", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class getStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public status As ServiceGuia.statusResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal status As ServiceGuia.statusResponse)
            MyBase.New
            Me.status = status
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sendBill", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class sendBillRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public fileName As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public contentFile() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public partyType As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal fileName As String, ByVal contentFile() As Byte, ByVal partyType As String)
            MyBase.New
            Me.fileName = fileName
            Me.contentFile = contentFile
            Me.partyType = partyType
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sendBillResponse", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class sendBillResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public applicationResponse() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal applicationResponse() As Byte)
            MyBase.New
            Me.applicationResponse = applicationResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sendPack", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class sendPackRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public fileName As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public contentFile() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public partyType As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal fileName As String, ByVal contentFile() As Byte, ByVal partyType As String)
            MyBase.New
            Me.fileName = fileName
            Me.contentFile = contentFile
            Me.partyType = partyType
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sendPackResponse", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class sendPackResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public ticket As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String)
            MyBase.New
            Me.ticket = ticket
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sendSummary", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class sendSummaryRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public fileName As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public contentFile() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public partyType As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal fileName As String, ByVal contentFile() As Byte, ByVal partyType As String)
            MyBase.New
            Me.fileName = fileName
            Me.contentFile = contentFile
            Me.partyType = partyType
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="sendSummaryResponse", WrapperNamespace:="http://service.sunat.gob.pe", IsWrapped:=true)>  _
    Partial Public Class sendSummaryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.sunat.gob.pe", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public ticket As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ticket As String)
            MyBase.New
            Me.ticket = ticket
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface billServiceChannel
        Inherits ServiceGuia.billService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class billServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceGuia.billService)
        Implements ServiceGuia.billService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceGuia_billService_getStatus(ByVal request As ServiceGuia.getStatusRequest) As ServiceGuia.getStatusResponse Implements ServiceGuia.billService.getStatus
            Return MyBase.Channel.getStatus(request)
        End Function
        
        Public Function getStatus(ByVal ticket As String) As ServiceGuia.statusResponse
            Dim inValue As ServiceGuia.getStatusRequest = New ServiceGuia.getStatusRequest()
            inValue.ticket = ticket
            Dim retVal As ServiceGuia.getStatusResponse = CType(Me,ServiceGuia.billService).getStatus(inValue)
            Return retVal.status
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceGuia_billService_getStatusAsync(ByVal request As ServiceGuia.getStatusRequest) As System.Threading.Tasks.Task(Of ServiceGuia.getStatusResponse) Implements ServiceGuia.billService.getStatusAsync
            Return MyBase.Channel.getStatusAsync(request)
        End Function
        
        Public Function getStatusAsync(ByVal ticket As String) As System.Threading.Tasks.Task(Of ServiceGuia.getStatusResponse)
            Dim inValue As ServiceGuia.getStatusRequest = New ServiceGuia.getStatusRequest()
            inValue.ticket = ticket
            Return CType(Me,ServiceGuia.billService).getStatusAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceGuia_billService_sendBill(ByVal request As ServiceGuia.sendBillRequest) As ServiceGuia.sendBillResponse Implements ServiceGuia.billService.sendBill
            Return MyBase.Channel.sendBill(request)
        End Function
        
        Public Function sendBill(ByVal fileName As String, ByVal contentFile() As Byte, ByVal partyType As String) As Byte()
            Dim inValue As ServiceGuia.sendBillRequest = New ServiceGuia.sendBillRequest()
            inValue.fileName = fileName
            inValue.contentFile = contentFile
            inValue.partyType = partyType
            Dim retVal As ServiceGuia.sendBillResponse = CType(Me,ServiceGuia.billService).sendBill(inValue)
            Return retVal.applicationResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceGuia_billService_sendBillAsync(ByVal request As ServiceGuia.sendBillRequest) As System.Threading.Tasks.Task(Of ServiceGuia.sendBillResponse) Implements ServiceGuia.billService.sendBillAsync
            Return MyBase.Channel.sendBillAsync(request)
        End Function
        
        Public Function sendBillAsync(ByVal fileName As String, ByVal contentFile() As Byte, ByVal partyType As String) As System.Threading.Tasks.Task(Of ServiceGuia.sendBillResponse)
            Dim inValue As ServiceGuia.sendBillRequest = New ServiceGuia.sendBillRequest()
            inValue.fileName = fileName
            inValue.contentFile = contentFile
            inValue.partyType = partyType
            Return CType(Me,ServiceGuia.billService).sendBillAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceGuia_billService_sendPack(ByVal request As ServiceGuia.sendPackRequest) As ServiceGuia.sendPackResponse Implements ServiceGuia.billService.sendPack
            Return MyBase.Channel.sendPack(request)
        End Function
        
        Public Function sendPack(ByVal fileName As String, ByVal contentFile() As Byte, ByVal partyType As String) As String
            Dim inValue As ServiceGuia.sendPackRequest = New ServiceGuia.sendPackRequest()
            inValue.fileName = fileName
            inValue.contentFile = contentFile
            inValue.partyType = partyType
            Dim retVal As ServiceGuia.sendPackResponse = CType(Me,ServiceGuia.billService).sendPack(inValue)
            Return retVal.ticket
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceGuia_billService_sendPackAsync(ByVal request As ServiceGuia.sendPackRequest) As System.Threading.Tasks.Task(Of ServiceGuia.sendPackResponse) Implements ServiceGuia.billService.sendPackAsync
            Return MyBase.Channel.sendPackAsync(request)
        End Function
        
        Public Function sendPackAsync(ByVal fileName As String, ByVal contentFile() As Byte, ByVal partyType As String) As System.Threading.Tasks.Task(Of ServiceGuia.sendPackResponse)
            Dim inValue As ServiceGuia.sendPackRequest = New ServiceGuia.sendPackRequest()
            inValue.fileName = fileName
            inValue.contentFile = contentFile
            inValue.partyType = partyType
            Return CType(Me,ServiceGuia.billService).sendPackAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceGuia_billService_sendSummary(ByVal request As ServiceGuia.sendSummaryRequest) As ServiceGuia.sendSummaryResponse Implements ServiceGuia.billService.sendSummary
            Return MyBase.Channel.sendSummary(request)
        End Function
        
        Public Function sendSummary(ByVal fileName As String, ByVal contentFile() As Byte, ByVal partyType As String) As String
            Dim inValue As ServiceGuia.sendSummaryRequest = New ServiceGuia.sendSummaryRequest()
            inValue.fileName = fileName
            inValue.contentFile = contentFile
            inValue.partyType = partyType
            Dim retVal As ServiceGuia.sendSummaryResponse = CType(Me,ServiceGuia.billService).sendSummary(inValue)
            Return retVal.ticket
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceGuia_billService_sendSummaryAsync(ByVal request As ServiceGuia.sendSummaryRequest) As System.Threading.Tasks.Task(Of ServiceGuia.sendSummaryResponse) Implements ServiceGuia.billService.sendSummaryAsync
            Return MyBase.Channel.sendSummaryAsync(request)
        End Function
        
        Public Function sendSummaryAsync(ByVal fileName As String, ByVal contentFile() As Byte, ByVal partyType As String) As System.Threading.Tasks.Task(Of ServiceGuia.sendSummaryResponse)
            Dim inValue As ServiceGuia.sendSummaryRequest = New ServiceGuia.sendSummaryRequest()
            inValue.fileName = fileName
            inValue.contentFile = contentFile
            inValue.partyType = partyType
            Return CType(Me,ServiceGuia.billService).sendSummaryAsync(inValue)
        End Function
    End Class
End Namespace
